### ISSUE TITLE
Need Help to Edit XBIN4 in Kirby and the Forgotten Land

### ISSUE THREAD

**Issue by JokerDKha** [firubii/MintWorkshop#1]
Thank's for you hard work, i need help to edit this XBIN4 file for translation this game.
Sample file:
[Filter.zip](https://github.com/firubii/MintWorkshop/files/8251296/Filter.zip)
One again thank you again for all hard work to make this tool.

**Comment by firubii** [comment]
msg/Kirby15/Filter.bin isn't related to text editing or mint/basil editing, its only purpose is filtering input text; use [Kuriimu](https://github.com/IcySon55/Kuriimu) for text editing
