### ISSUE TITLE
(Kirby: Triple Deluxe) Step.bin.cmp builds an invalid file

### ISSUE THREAD

**Issue by kumquatbaguette** [firubii/MintWorkshop#2]
Pretty much what the title says. Trying to build even an unedited duplicate of the Step.bin.cmp file in Triple Deluxe creates a corrupted file that crashes the game and freezes Mint Workshop if loaded. No idea what could be causing it.

**Comment by firubii** [comment]
this has actually already been fixed, i just haven't released a version with the fix yet
